---
  - name: Install Docker
    hosts: ucp.brick-house.org
    roles:
      - role: docker
        tags:
          - docker
        become: yes
      - role: gcp
        tags:
          - gcp
        become: yes
      - role: ucp
        tags:
          - ucp
