---
- name: Add gcs fuse repo.
  apt_repository:
    repo: 'deb http://packages.cloud.google.com/apt gcsfuse-bionic main'
    state: present
    update_cache: yes
- name: Add gpg key for repo.
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
- name: Update cache, upgrade packages.
  apt:
    update_cache: yes
    upgrade: full
- name: Install FUSE
  apt:
    name: gcsfuse
    state: present
- name: Update user.
  user:
    name: "{{ username }}"
    groups: fuse
    append: yes
    state: present
