---
- name: Update apt cache.
  apt:
    update_cache: yes
- name: Install ntpd.
  apt:
    name: ntp
    state: present
- name: Create the partition.
  parted:
    device: /dev/sdb
    label: gpt
    name: gluster
    number: 1
    state: present
- name: Format the fs for bricks.
  filesystem:
    dev: /dev/sdb1
    fstype: xfs
- name: Create the data directory.
  file:
    dest: /data/glusterfs/money/bricks
    state: directory
- name: Mount the filesystem
  mount:
    path: /data/glusterfs/money/bricks
    src: /dev/sdb1
    state: mounted
    fstype: xfs
    backup: yes
  become: yes
