---
- name: Add correct repo for glusterfs.
  apt_repository:
    repo: ppa:gluster/glusterfs-6
    state: present
    update_cache: yes
- name: Install glusterfs.
  apt:
    update_cache: yes
    name: glusterfs-server
- name: Install ntpd.
  apt:
    name: ntp
    state: present
- name: Start and enable service.
  service:
    name: glusterd
    state: started
    enabled: yes
- name: Create the partition.
  parted:
    device: /dev/sdb
    label: gpt
    name: gluster
    number: 1
    state: present
- name: Format the fs for bricks.
  filesystem:
    dev: /dev/sdb1
    fstype: xfs
- name: Mount the filesystem
  mount:
    path: /mnt
    src: /dev/sdb1
    state: mounted
    fstype: xfs
    backup: yes
  become: yes
