---
- name: Add coorect repo for glusterfs.
  apt_repository:
    repo: ppa:gluster/glusterfs-6.1
    state: present
    update_cache: yes
- name: Install glusterfs.
  apt:
    update_cache: yes
    name: glusterfs-server
