---
- name: Add correct repo for glusterfs.
  apt_repository:
    repo: ppa:gluster/glusterfs-6
    state: present
    update_cache: yes
- name: Install glusterfs.
  apt:
    update_cache: yes
    name: glusterfs-server
- name: Create a trusted storage pool
  gluster_peer:
    state: present
    nodes:
      - manager
      - worker1
      - worker2
  tags:
    - pool
- name: Create brick directory.
  file:
    path: /mnt/bricks
    state: directory
  tags:
    - bricks
- name: create gluster volume
  gluster_volume:
    state: present
    name: money
    brick: /mnt/bricks
    rebalance: yes
    cluster:
      - manager
      - worker1
      - worker2
  run_once: true
  tags:
    - volumes
- name: start gluster volume
  gluster_volume:
    state: started
    name: money
  tags:
    - volumes
- name: Mount the glusterfs volume.
  mount:
    path: /srv/money
    src: worker1:/money
    state: mounted
    fstype: glusterfs
    backup: yes
  become: yes
  tags:
    - mount_gluster
- name: Mount the glusterfs volume.
  mount:
    path: /srv/money
    src: worker1:/money
    state: unmounted
    fstype: glusterfs
    backup: yes
  become: yes
  tags:
    - unmount_gluster
