---
- name: Add correct repo for glusterfs.
  apt_repository:
    repo: ppa:gluster/glusterfs-6
    state: present
    update_cache: yes
- name: Install glusterfs.
  apt:
    update_cache: yes
    name: glusterfs-server
- name: Create a trusted storage pool
  gluster_peer:
    state: present
    nodes:
      - manager
      - worker1
      - worker2
  tags:
    - pool
- name: Create brick directory.
  file:
    path: /mnt/bricks/brick1/money1
    state: directory
  tags:
    - bricks
- name: create gluster volume
  gluster_volume:
    state: present
    name: money
    brick: /mnt
    rebalance: yes
    cluster:
      - manager
      - worker1
      - worker2
  run_once: true
  tags:
    - volumes
- name: start gluster volume
  gluster_volume:
    state: started
    name: money
  tags:
    - volumes
