---
- name: Deploy UCP
  docker_container:
    auto_remove: yes
    command:
      - install
      - --admin-password
      - password
      - --admin-username
      - admin
    image: docker/ucp
    name: ucp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
