---
- name: uninstall old versions
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - docker
    - docker-engine
    - docker-ce
    - docker.io
- name: update apt repository
  apt:
    update_cache: yes
- name: Install packages.
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ install_apt_packages }}""
- name: Install pips.
  pip:
    name: docker
    state: present
- name: Add apt key.
  apt_key:
    url: "{{ docker_ee_url }}/ubuntu/gpg"
    state: present
- name: Add apt repo.
  apt_repository:
    repo: "deb [arch=amd64] \
      {{ docker_ee_url }}/ubuntu bionic stable-{{ docker_ee_version }}"
    state: present
- name: Update apt cache.
  apt:
    update_cache: yes
- name: Install Docker.
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ee
    - docker-ee-cli
    - containerd.io
- name: Upgrade apt.
  apt:
    upgrade: full
