---
- name: uninstall old versions
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - docker
    - docker-engine
    - docker-ce
    - docker.io
- name: update apt repository
  apt:
    update_cache: yes
- name: Install packages.
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
- name: Add apt key.
  apt_key:
    url: "{{ docker_ee_url }}/ubuntu/gpg"
    state: present
- name: Add apt repo.
  apt_repository:
    repo: "deb [arch=x86_64] \
      {{ docker_ee_url }}/ubuntu bionic stable-{{ docker_ee_version }}"
    state: present
